### ISSUE TITLE
FlashLoan Fee check is wrong

### ISSUE THREAD

**Issue by guoyiteng** [saddle-finance/saddle-contract#344]
I was trying out the flashloan and noticed that I couldn't repay the loan with exactly the borrowed amount plus the fee. After examining the contract, I found that the `require` check to test if the fee is repaid was wrong. `protocolBalanceBefore` should not subtracted when calculating `availableLiquidityAfter`. The current check fails when the repaid fee is smaller than `fee + protocolBalance`, which means users have to pay more fees than they should when calling flash loan.

https://github.com/saddle-finance/saddle-contract/blob/master/contracts/SwapFlashLoan.sol#L132

**Comment by penandlim** [comment]
Confirmed the issue. In case when `protocolBalance > 0`, flash loan borrowers need to pay more than the quoted fee. There is no imminent impact on existing LPs.
