### ISSUE TITLE
tokenAmount issue

### ISSUE THREAD

**Issue by hermitsgame** [saddle-finance/saddle-contract#484]
https://github.com/saddle-finance/saddle-contract/blob/master/contracts/SwapUtils.sol#L215

require(tokenAmount <= xp[tokenIndex], "Withdraw exceeds available");

It seems that tokenAmount is the amount of LP, But the code compares it with xp of pool token.

**Comment by hermitsgame** [comment]
@alphastorm @penandlim

**Comment by kyriediculous** [comment]
The amount of LP tokens you receive can never be greater than the combined amount of tokens you deposit. Hence the totalSupply of LP tokens can never be greater than the token reserves in the pool. 

E.g. if you have a fresh pool of e.g. DAI/UST and you add 100 tokens of each to the pool you will receive 200 LP tokens in return. 

If you then want to make a single sided withdrawal for DAI and you want to withdraw for 200 LP tokens then that would have to represent 200 DAI, but there is only 100 DAI in the pool.

**Comment by penandlim** [comment]
This is intended as @kyriediculous pointed out. When withdrawing via one token, the amount of LP tokens you burn cannot be more than the available liquidity in the pool.
