### ISSUE TITLE
Remove lpTokenName field from permissionless pool creation

### ISSUE THREAD

**Issue by penandlim** [saddle-finance/saddle-contract#556]
Currently permissionless deployer accepts lpTokenName as one of the parameter inputs.
There is not a good reason for custom lp token names.

permissionless swaps' LP token names should be formatted to
`Saddle {lpTokenSymbol} LP Token`

https://ethereum.stackexchange.com/a/56337

**Comment by mjdatadog** [comment]
PR was merged [here](https://github.com/saddle-finance/saddle-contract/commit/21b722d576fd2b75e6551e3fe15b51cc4fba3b72) then deleted. Closing issue.
