### ISSUE TITLE
Add helper function for gauge rewards

### ISSUE THREAD

**Issue by hammeiam** [saddle-finance/saddle-contract#576]
Use the helper contract to create a call `getGaugeRewards(gauge address)` to return all rewards

https://www.notion.so/saddle-finance/Gauge-Data-1919b6d6317245baa5f58cc25b17ed98#9c3c3dc123394343b73823e6460820a0

**Comment by mjdatadog** [comment]
Closing issue as branch was merged [here](https://github.com/saddle-finance/saddle-contract/commit/a0ece670bfe60c0dbeb9b46fff64e417a5509afd) then deleted
